/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tom' at '8/2/15 8:45 AM' with Gradle 2.5-rc-2
 *
 * @author Tom, @date 8/2/15 8:45 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
